# ./docker-compose.yml

# version: '3'
# services:
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=
#       - POSTGRES_DB=
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#   web:
#     build: .
#     # command: bundle exec rails s -b 0.0.0.0
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/home/app
#       - bundle:/bundle
#     environment:
#       RAILS_ENV: development
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
# volumes:
#   postgres-data:
#     driver: local
#   bundle:
#     driver: local

version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/deep_space_9
    ports:
      - "3000:3000"
    depends_on:
      - db
